#!/bin/bash

dest="$HOME/brewupdate.log"
usage="\e[1mbru\e[0m [-h]"
help="An updater script for homebrew.
$usage
	\e[1m-h\e[0m	Displays this message and exits.
Executes the commands: brew update, brew upgrade, brew cleanup, brew doctor
Logs the results to $dest.
"

trap "echo 'Interrupted.' | tee -a $dest; end; exit 1" 2

case $1 in
  -h|--help)
    printf "$help"
    exit 0
    ;;
  -*)
    printf "Wrong argument: %s\n$usage -- See -h for more help.\n" "$1"
    exit 1
    ;;
  "")
    ;;
  *)
    echo "Arguments will be ignored."
    ;;
esac

end() {
  printf "END on $(date)\n%s\n" >> $dest "******************************************"
}

start() {
  printf "START on $(date)\n" >> $dest
}

runCmd() {
  title=$(echo "$@" | awk '{print toupper($0)}')
  echo "$title" && "$@" 2>&1 | tee /dev/tty | while IFS= read -r line; do printf "%s: %s\n" "$(date +'%Y-%m-%d %T')" "$line"; done >> "$dest"
}

#test internet connection
waitnet -s || exit 1

start

nver_before=$(nativefier --version)

runCmd brew update
runCmd brew upgrade
runCmd brew cleanup
runCmd brew doctor

nver_after=$(nativefier --version)

if [[ $nver_before != $nver_after ]]; then
  trash "/Applications/Duolingo.app" &>/dev/null
  trash "/Applications/Graphing Calculator.app" &>/dev/null
  trash "/Applications/Trading212.app" &>/dev/null
  sys_install
fi

# hash mas &>/dev/null && runCmd mas upgrade
# softwareupdate --all --install

end
