#!/bin/bash

git status >/dev/null || exit 1

if [[ -z $1 ]]; then
  committers=($(git shortlog --summary --numbered --email | grep -o '<.*>' | sed 's/^<//;s/>$//'))
else
  committers=($@)
fi

f_gitcnt() {
  git log --shortstat --author "$1" | grep "files\? changed" | awk '{inserted+=$4; deleted+=$6} END {print "Lines inserted:", inserted, "\t Lines deleted:", deleted}'
}

[[ "${#committers[@]}" -gt 1 ]] && multi=1

for committer in ${committers[@]}; do
  if [[ $multi ]]; then
    echo
    echo "$committer:"
  fi
  f_gitcnt "$committer"
done
